#! python3
DANHz6EQVoWyZ9rER56DwTXHWUxfkv9k2o
print("hello)

thm{"Can you guess what this is, now?"}

0x52908400098527886E0F7030069857D2E4169EE730000000000004

@pytest.mark.skip(reason="Fails Regex due to http://")
"1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY"


thm{"uh hello?"}
001-01-0001
flag{"helo jenny dwi'n gwybod eich bod chi'n darllen hwn diolch am fod yn ffrind i mi "}
340000000000009
http://10.1.1.1
https://www.youtube.com/watch?v=ScOAntcCa78
adsadasdasdhttps://www.youtube.com/watch?v=trj15fjXWDwasdasdasd
6011000000000004
htb{4111111111111111}
3000 0000 0000 04
5500000000000004

james:S3cr37_P@$$W0rd
ScOAntcCa78
<h1> hello </h2>
127.0.0.1
github@skerritt.blog
