#! python3
DANHz6EQVoWyZ9rER56DwTXHWUxfkv9k2o
print("hello)

thm{"Can you guess what this is, now?"}

0x52908400098527886E0F7030069857D2E4169EE7

@pytest.mark.skip(reason="Fails Regex due to http://")
"1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY"


thm{"uh hello?"}

flag{"helo jenny dwi'n gwybod eich bod chi'n darllen hwn diolch am fod yn ffrind i mi "}

http://10.1.1.1


htb{4111111111111111}
3000 0000 0000 04
5500000000000004
